server:
  port: 9500
  servlet:
    context-path: /redisserver
spring:
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        #等待可用连接的最大时间，负数为不限制
        max-wait: 20s
        #最大连接数  负数不限制
        max-active: -1
        #最小空闲连接数
        min-idle: 10
        #最大空闲连接数
        max-idle: 20
    password:
    host: 127.0.0.1